from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
README_PATH = ROOT / "README.md"


def _scan_repo_tree() -> str:
    include_roots = [".github", "config", "data", "scripts", "src"]
    excluded_parts = {".git", "__pycache__", "processed_orders"}
    lines = []
    for root in include_roots:
        path = ROOT / root
        if not path.exists():
            continue
        lines.append(f"- `{root}/`")
        for sub in sorted(path.rglob("*")):
            if any(part in excluded_parts for part in sub.parts):
                continue
            rel = sub.relative_to(ROOT)
            depth = len(rel.parts) - 1
            indent = "  " * (depth + 1)
            suffix = "/" if sub.is_dir() else ""
            lines.append(f"{indent}- `{rel}{suffix}`")
    return "\n".join(lines)


def build_readme() -> str:
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    return f"""# Spark Data Engineering Workflow Template

This repository provides an industry-standard starter layout for a PySpark ETL workflow.

## Project Overview
- Source: 10 sample CSV files (`data/input`) with 5 records each.
- Processing: Read CSV, apply filters, perform joins, and enrich using `withColumn`.
- Sink: CSV output written to `data/output/processed_orders`.

## Folder Structure
{_scan_repo_tree()}

## PySpark Pipeline
1. Read `customers_*.csv` and `orders_*.csv` files.
2. Filter orders where `amount >= 200`.
3. Join orders with customers using `customer_id`.
4. Create additional columns:
   - `amount_with_tax`
   - `order_month`
   - `ingestion_ts`
5. Write transformed output as CSV.

## How to Run
```bash
PYTHONPATH=src python -m workflowtest.jobs.workflowtest_job
```

## GitHub Workflow Automation
- Workflow: `.github/workflows/copilot-readme-sync.yml`
- Trigger: every `push` and `pull_request`
- Behavior:
  - regenerates `README.md` after scanning repository files
  - commits README updates automatically when content changes

_Last autogenerated update: {timestamp}_
"""


def main() -> None:
    README_PATH.write_text(build_readme(), encoding="utf-8")


if __name__ == "__main__":
    main()
